baseURL = 'https://nathnkim.github.io/Notebook/'
languageCode = 'en-us'
title = 'nkbuilds'
pluralizeListTitles = 'false'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true